### PR TITLE
build(github): add a lint workflow

### PR DESCRIPTION
**Pull request by tchaikov**
for checking the clang-format compliance.

Signed-off-by: Kefu Chai <tchaikov@gmail.com>

### CODE REVIEW

**Comment by tchaikov** [comment]
see https://github.com/tchaikov/co_context/actions/runs/3321795445/jobs/5489930807 for a test run

**Comment by Codesire-Deng** [comment]
Thank you! I learned from it. Could you please modify a bit the `clang-format-check.yml`? Just like:

```yaml
name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '15'
        check-path: '.'
        exclude-regex: 'include/uring/.*\.h$'
```

That could be more like the official demo from [jidicula/clang-format-action](https://github.com/jidicula/clang-format-action), and more precise on `exclude-regex`. Thank you!

**Comment by tchaikov** [comment]
@Codesire-Deng i don't really want to *copy* the example or follow it without good reasons. and could you help me understand the reason to do so? 

regarding "more precise on `exclude-regex`", would you please shed some light on the rationales behind it?

**Comment by Codesire-Deng** [comment]
@tchaikov Oh, my opinion is that a text similar to the official one can make it easier for us to recall what we had done to it. When we come back next time (for update), we can check the difference between the the latest demo and ours. 

Of course, it's just an *cv-engineer*'s habit. 🤣

**Comment by tchaikov** [comment]
IMHO, the "official one" is but a demo. it is not supposed to be a best practice.

>  it easier for us to recall what we had done to it. 

we are not adapt to an existing implementation or something. what we are trying to accomplish is but to use a tool with a well defined interface.

**Comment by Codesire-Deng** [comment]
> what does "cv-engineer" stand for?

I mean "Ctrl-C Ctrl-V engineer", the guy who like to keep the same as the examples rather than to rewrite them, if it makes no difference.

(Note that "cv" of "cv-engineer" sometimes stands for Computer Vision.)

**Comment by tchaikov** [comment]
TIL =)

fair enough. i am happy to close this PR without any bad feelings, if you are in favor of copying the example. as this workflow is more like a guard for future contributors. but it's not that urgent considering the external contributors at this moment.

please note, i am not trying to "rewrite" the demo, i use it as a reference. that's all.

**Comment by Codesire-Deng** [comment]
Thanks again for that advice. I will remember it as an option.

**Pull request closed without merging**
